# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: math-util-mvn

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
  
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 18 
      uses: actions/setup-java@v3 # Khai báo cần dùng JDK để build
      with:
          java-version: '18' # Khai báo sử dụng phiên bản JDK 18 để build
          distribution: 'temurin'
          cache: maven
     
    - name: Build project with Maven
      run: mvn -B package --file pom.xml # Quá trình build sẽ cần đến file cấu hình pom.xml
      
    - name: Distribute jar-war file # Gửi file .jar .war đi đâu, CD nhảy vào ...
      run: mkdir staging && cp target/*.jar staging # tạo thư mục staging chứa file .jar .war sau khi build      
     
    - name: Make hyperlink to jar-war file # Tạo hyperlink để download build 
      uses: actions/upload-artifact@v1
      with:
        name: 1.0-SNAPSHOT.jar # Bản build được đánh version 1.0-SNAPSHOT
        path: staging
